server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 39.100.249.228:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
