server:
  port: 8300


spring:
  application:
    name: nacos-consumer-provider
  cloud:
    nacos:
      discovery:
        server-addr: 39.100.249.228:8848 #配置Nacos地址

#消费者将去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider