
server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinal-service
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 39.100.249.228:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      datasource:
        ds1:
          nacos:
            server-addr: 39.100.249.228:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true





