server:
  port: 8006
spring:
  application:
    name: cloud-consul-payment8006

  cloud:
    consul:
      host: 39.100.249.228
      port: 8500
      discovery:
        service-name: ${spring.application.name}

management:
  endpoint:
    beans:
      enabled: false