server:
  port: 8080
spring:
  application:
    name: order-feign-service
  zipkin:
    base-url: http://39.100.249.228:9411
  sleuth:
    sampler:
      #采样取值介于 0到1之间，1则表示全部收集
      probability: 1
eureka:
  client:
  # false表示不向注册中心注册自己
     register-with-eureka: true
    # false表示自己端就是注册中心,我的职责就是维护服务实例,并不需要检索服务
     fetch-registry: true
     service-url:
         # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
              # 单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
              # 相互注册
              #defaultZone: http://eureka7002.com:7002/eureka/
        defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的实际
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控那个接口
    com.eiletxie.springcloud.service.PaymentFeignService: debug

